#
# Read the Docs configuration file
#

# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml

# Python environment for building docs
python:
  install:
    # Install your project so mkdocstrings (or other tools) can import it
    - method: pip
      path: .

    # Docs dependencies (MkDocs + plugins)
    - requirements: docs/requirements.txt
